config/routes.rb
Rails.application.routes.draw do

  resources :ngos, except: [:index] do

    resources :requests
    resources :projects, except: [:index, :show, :edit, :update, :destroy]
    # Projects
    get 'search', to: 'projects#search', as: :project_search
    get 'projects', to: 'ngos#projects', as: :projects, on: :member


    post 'join', to: 'ngos#join', as: :join, on: :member
    get 'join-ngo', to: 'ngos#select', as: :join, on: :collection
    put 'make_admin', to: 'ngos#make_admin', as: :make_admin
    put 'make_worker', to: 'ngos#make_worker', as: :make_worker
    put 'stoping_admin', to: 'ngos#stoping_admin', as: :stoping_admin
    delete 'destroy_association', to: 'ngos#destroy_association', as: :destroy_association, on: :member

    resources :participants, except: [:new, :create]
    #resources :participants, except: [:new, :create]

    get 'team/:team_id/participants/new', to: 'participants#new', as: :new_participant
    post 'team/:team_id/participants', to: 'participants#create', as: :create_participant
  end

  get 'my-ngos', to: 'ngos#my_ngos', as: :my_ngos

  resources :teams, except: :index do
    member do
      put 'add-participant/:participant_id', to: 'teams#add_participant', as: :add_participant
      put 'remove-participant_team/:participant_id', to: 'teams#remove_participant', as: :remove_participant
      put 'make-leader/:participant_id', to: 'teams#make_leader', as: :make_leader
      put 'make-regular/:participant_id', to: 'teams#make_regular', as: :make_regular
    end
  end

  resources :projects, only: [:index, :show, :edit, :update, :destroy, :add_user, :delete_user] do
    member do
      put 'add_user', to: 'projects#add_user', as: :add_user
      put 'delete_user', to: 'projects#delete_user', as: :delete_user
    end
  end

  get 'search', to: 'projects#search', as: :project_search
  delete 'handle-request', to: 'requests#handle', as: :handle_request
  get 'requests', to: 'requests#index', as: :requests

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  as :user do
    get     'sign-up', to: 'devise/registrations#new', as: :sign_up
    get     'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign-out', to: 'devise/sessions#destroy', as: :sign_out
    get    'profile',  to: 'devise/registrations#edit', as: :profile
  end

  get 'not-found', to: 'pages#not_found', as: :not_found
  get '/change_locale/:locale', to: 'locales#change_locale', as: :change_locale

  root 'pages#home'


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ngo.rb
# == Schema Information
#
# Table name: ngos
#
#  id         :integer          not null, primary key
#  name       :string
#  country    :string
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ngo < ApplicationRecord
  validates :name, presence: true, length: {maximum: 200}
  validates :country, presence: true, length: {maximum: 200}
  has_many :ngo_users, dependent: :destroy
  has_many :users, through: :ngo_users
  has_many :requests
  has_many :projects

  scope :without_user, ->(user_id) { where.not(id: NgoUser.where(user_id: user_id).pluck(:ngo_id))}
  scope :with_admin, -> (user_id) { where(id: NgoUser.where(user_id: user_id, admin: true).pluck(:ngo_id))}
  mount_uploader :image, NgoImageUploader

  def admins
    User.where(id: NgoUser.where(ngo_id: self.id, admin: true).pluck(:user_id))
  end

  def workers
    User.where(id: NgoUser.where(ngo_id: self.id, admin: false).pluck(:user_id))
  end

  def is_admin?(user)
    admins.pluck(:id).include?(user.id)
  end

  def remove_user(user_id)
    NgoUser.where(user_id: user_id, ngo_id:self.id).destroy_all
  end

  def add_admin(user)
    if user
      if users.include?(user)
        NgoUser.where(ngo_id: id, user_id: user.id).update(admin: true)
      else
        NgoUser.create(ngo_id: id, user_id: user.id, admin: true)
      end
    end
  end

  def add_worker(user)
    if user
      if users.include?(user)
        NgoUser.where(ngo_id:self.id, user_id: user.id).update(admin: false)
      else
        NgoUser.create(user_id: user.id, ngo_id:self.id, admin: false)
      end
    end
  end

  def last_admin
    NgoUser.where(ngo_id:self, admin:true).count==1
  end

  def my_ngos(user_id)
    Ngo.find(NgoUser.where(user_id:user_id).pluck(:ngo_id))
  end
end

app/controllers/ngos_controller.rb
class NgosController < ApplicationController

  before_action :set_ngo, except: [:my_ngos, :select, :new, :create]
  before_action :authenticate_user!
  before_action :is_admin, except: [:show, :my_ngos, :select, :new, :create, :projects, :join]
  before_action :set_breadcrumbs

  # GET /my_ngos
  def my_ngos
    @ngos = current_user.ngos
  end

  def select
    @ngos= Ngo.without_user(current_user.id)
  end
  # GET /ngos/1
  # GET /ngos/1.json
  def show
    @check= params[:check]
    @breadcrumbs << {text: @ngo.name, path: ngo_path(@ngo)}
  end

  # GET /ngos/new
  def new
    @breadcrumbs << {text: t(".breadcrumb_new"), path: new_ngo_path}
    @ngo = Ngo.new
  end

  # GET /ngos/1/edit
  def edit
    @breadcrumbs << {text: @ngo.name, path: ngo_path(@ngo)}
    @breadcrumbs << {text: t(".breadcrumb_edit"), path: edit_ngo_path(@ngo)}
  end

  # POST /ngos
  # POST /ngos.json
  def create
    @ngo = Ngo.new(ngo_params)
    if @ngo.save
      @ngo_user = NgoUser.create(user_id: current_user.id, ngo_id:@ngo.id, admin:true)
      if @ngo_user.save
        redirect_to @ngo, flash: {success: t(".success")}
      else
        redirect_to @ngo, flash: {warning: t(".warning")}
      end
    else
      render :new
    end
  end

  # PATCH/PUT /ngos/1
  # PATCH/PUT /ngos/1.json
  def update
    respond_to do |format|
      if @ngo.update(ngo_params)
        format.html { redirect_to @ngo, notice: t(".notice") }
        format.json { render :show, status: :ok, location: @ngo }
      else
        format.html { render :edit }
        format.json { render json: @ngo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ngos/1
  # DELETE /ngos/1.json
  def destroy
    @ngo.destroy
    respond_to do |format|
      format.html { redirect_to my_ngos_path, notice: t(".notice") }
      format.json { head :no_content }
    end
  end

  def join
    @breadcrumbs << {text: t(".breadcrumb_join"), path: join_ngo_path(@ngo)}
    if !(@ngo.users.pluck(:id).include?(current_user.id))
      @request = Request.create(user_id: current_user.id, ngo_id:@ngo.id)
      if @request.save
        flash.now[:notice] = t(".notice")
        @ngos= Ngo.without_user(current_user.id)
        render :select
      else
        redirect_to ngos_url, warning: t(".warning")
      end
    else
      flash.now[:notice] = t(".warning")
      @ngos= Ngo.without_user(current_user.id)
      render :select
    end

  end

  def make_admin
    if @ngo.is_admin?(User.find(params[:user]))
      redirect_to ngo_path(params[:ngo_id]), notice: "This User Already is admin."
    else
      if !@ngo.is_admin?(current_user)
        redirect_to root_path
      else
        NgoUser.find_by(user_id:params[:user], ngo_id:@ngo.id).update(admin: true)
        redirect_to ngo_path(params[:ngo_id]), notice: t(".notice")
      end
    end
  end

  def make_worker
    if @ngo.last_admin
      redirect_to ngo_path(@ngo.id), notice: t(".warning")
    else
      NgoUser.find_by(user_id:params[:user], ngo_id:@ngo.id).update(admin: false)
      redirect_to ngo_path(@ngo.id), notice: t(".notice")
    end
  end

  def destroy_association
    user = User.find(params[:user])
    if @ngo.last_admin && @ngo.is_admin?(user)
      message = t(".notice.delete")
    elsif @ngo.remove_user(params[:user])
      message = t(".notice.disassociate")
    else
      message = t(".notice.error")
    end
    redirect_to @ngo, notice: message
  end

  def projects
    @message_when_empty = t(".notice")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ngo
      if params[:id]
        @ngo = Ngo.find(params[:id])
      else
        @ngo = Ngo.find(params[:ngo_id])
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: 'This ngo does not exist'
    end

    def is_admin
      unless @ngo.is_admin?(current_user)
        redirect_to root_path, notice: t(".is_admin.notice")
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ngo_params
      params.require(:ngo).permit(:name, :country, :image)
    end

    def ngo_user_params
      params.require(:ngouser).permit(:user_id, :ngo_id, :admin)
    end

    def set_breadcrumbs
      @breadcrumbs =
      [
        {text:  t(".set_breadcrumbs.index"), path: root_path },
        {text: "Ngos", path: my_ngos_path }
      ]
    end
end

app/helpers/ngos_helper.rb
module NgosHelper
  def ngo_avatar ngo
    if ngo.image.present?
      image_tag ngo.image_url :thumbnail
    else
      image_tag 'images.jpg'
    end
  end
end

app/views/ngos/_form.html.haml
= render 'layouts/errors', resource: @ngo
= form_for @ngo do |f|
  .form-group
    = f.label t(".label_name")
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label t(".label_country")
    = f.text_field :country, class: "form-control"
  .form-group
    = f.label t(".label_image")
    = f.file_field :image, class: "form-control", accept: 'image/jpeg,image/gif,image/png'

  = f.submit t(".submit_button"), class: "btn btn-primary"

app/views/ngos/_ngo.html.haml
%li.list-group-item.d-flex.justify-content-between.align-items-center
  = link_to ngo.name, ngo_path(ngo.id)
  - if ngo.is_admin?(current_user)
    .row
      = link_to t(".edit_button"), edit_ngo_path(ngo), class: "btn btn-primary mr-1"
      = link_to t(".delete_button"), ngo, method: "delete", class: "btn btn-danger", data: { confirm: t(".data_confirm")}

app/views/ngos/_user.html.haml
- if @ngo.users.count > 0
  - @ngo.users.each do |user|
    %li.list-group-item.d-flex.justify-content-between.align-items-center.row
      .col-7
        = user.name
        -unless @ngo.is_admin?(current_user)
          -if @ngo.is_admin?(user)
            .badge.badge-primary Admin
          -else
            .badge.badge-warning Worker
      .col-5
        -if @ngo.is_admin?(current_user)
          -if @ngo.is_admin?(user)
            = link_to t(".make_worker_button"), ngo_make_worker_path(:user=>user, :ngo_id=>@ngo.id), method: 'put', class: "btn btn-success btn-sm btn-block", data: { confirm: t(".data_confirm_stop")}
          -else
            = link_to t(".make_admin_button"), ngo_make_admin_path(:user=>user, :ngo_id=>@ngo), method: 'put', class: "btn btn-primary btn-sm btn-block"
          = link_to t(".delete_button"), destroy_association_ngo_path(:user=>user, id: @ngo), method: 'delete', class: "btn btn-danger btn-sm btn-block", data: { confirm: t(".data_confirm_delete")}
- else
  .alert.alert-warning.text-center #{t(".alert_warning")} #{@ngo.name}.

app/views/ngos/edit.html.haml
.row
  .col-md-4.offset-md-4
    %h1=t(".h1_edit")
    = render 'form'

app/views/ngos/my_ngos.html.haml
.row.bottom-bar-container
  .col-12.col-md-4.offset-md-4
    %h1.text-center NGO
    %ul.list-group
      = render @ngos

.col-md-4
  %nav.navbar.fixed-bottom.navbar-light.bg-light
    = button_to t(".new_button"), new_ngo_path, method: "get", class: "btn btn-success"

app/views/ngos/new.html.haml
.row
  .col-md-4.offset-md-4
    %h1=t(".h1_new")
    = render 'form'

app/views/ngos/projects.html.haml
= render 'projects/projects_list', projects: @ngo.projects, title: t('.title') + "#{@ngo.name} ", ngo_id: @ngo.id

app/views/ngos/select.html.haml
.row.bottom-bar-container
  .col-12.col-md-4.offset-md-4
    %h1.text-center NGO
    -@ngos.each do |ngo|
      %ul.list-group
        %li.list-group-item.d-flex.justify-content-between.align-items-center
          -if Request.where(user_id: current_user.id, ngo_id:ngo.id).exists?
            = link_to ngo.name, ngo_path(ngo.id)
            = link_to t(".request_button"), "#", class: "btn btn-warning mr-1"
          -else
            = link_to ngo.name, ngo_path(ngo.id)
            = link_to t(".join_button"), join_ngo_path(ngo.id), method: "post", class: "btn btn-success mr-1"

app/views/ngos/show.html.haml
.bottom-bar-container
  .row
    .col-12
      %h1.text-center
        =@ngo.name
    - if user_signed_in? && @ngo.is_admin?(current_user) || user_signed_in? && !@ngo.is_admin?(current_user)
      .col-12.text-center
        = link_to t(".main_title"), projects_ngo_path(@ngo), class: 'btn btn-success'
        = link_to t(".participants")+@ngo.name, ngo_participants_path(@ngo), method: "get", class: "btn btn-warning"
    .col-md-4.offset-md-2
      %h2.text-center=t(".detail_title")
      .card
        .card-body
          %p
            %b
            =t(".country")
            = @ngo.country
            %br
            =t(".admins")
            %ul
              - @ngo.admins.each do |admin|
                %li=admin.name
        = image_tag @ngo.image.url, class: "w-70 p-3", alt: ""
        -# = image_tag @ngo.image, class: "w-70 p-3", alt: ""
      - if @ngo.is_admin?(current_user)
        .text-center
          = link_to t(".edit_button"), edit_ngo_path(@ngo), class: "btn btn-primary mt-3"
          = link_to t(".back_button"), my_ngos_path, class: "btn btn-success mt-3"
    .col-md-4
      -# -if @ngo.is_admin?(current_user)
      %h2.text-center Associated Users
      = render 'user'

- if @ngo.is_admin?(current_user)
  .col-md-4
    %nav.navbar.fixed-bottom.navbar-light.bg-light
      = button_to t(".new_button"), new_ngo_project_path(@ngo), method: "get", class: "btn btn-success"