config/routes.rb
Rails.application.routes.draw do

  resources :ngos, except: [:index] do

    resources :requests
    resources :projects, except: [:index, :show, :edit, :update, :destroy]
    # Projects
    get 'search', to: 'projects#search', as: :project_search
    get 'projects', to: 'ngos#projects', as: :projects, on: :member


    post 'join', to: 'ngos#join', as: :join, on: :member
    get 'join-ngo', to: 'ngos#select', as: :join, on: :collection
    put 'make_admin', to: 'ngos#make_admin', as: :make_admin
    put 'make_worker', to: 'ngos#make_worker', as: :make_worker
    put 'stoping_admin', to: 'ngos#stoping_admin', as: :stoping_admin
    delete 'destroy_association', to: 'ngos#destroy_association', as: :destroy_association, on: :member

    resources :participants, except: [:new, :create]
    #resources :participants, except: [:new, :create]

    get 'team/:team_id/participants/new', to: 'participants#new', as: :new_participant
    post 'team/:team_id/participants', to: 'participants#create', as: :create_participant
  end

  get 'my-ngos', to: 'ngos#my_ngos', as: :my_ngos

  resources :teams, except: :index do
    member do
      put 'add-participant/:participant_id', to: 'teams#add_participant', as: :add_participant
      put 'remove-participant_team/:participant_id', to: 'teams#remove_participant', as: :remove_participant
      put 'make-leader/:participant_id', to: 'teams#make_leader', as: :make_leader
      put 'make-regular/:participant_id', to: 'teams#make_regular', as: :make_regular
    end
  end

  resources :projects, only: [:index, :show, :edit, :update, :destroy, :add_user, :delete_user] do
    member do
      put 'add_user', to: 'projects#add_user', as: :add_user
      put 'delete_user', to: 'projects#delete_user', as: :delete_user
    end
  end

  get 'search', to: 'projects#search', as: :project_search
  delete 'handle-request', to: 'requests#handle', as: :handle_request
  get 'requests', to: 'requests#index', as: :requests

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  as :user do
    get     'sign-up', to: 'devise/registrations#new', as: :sign_up
    get     'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign-out', to: 'devise/sessions#destroy', as: :sign_out
    get    'profile',  to: 'devise/registrations#edit', as: :profile
  end

  get 'not-found', to: 'pages#not_found', as: :not_found
  get '/change_locale/:locale', to: 'locales#change_locale', as: :change_locale

  root 'pages#home'


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id            :integer          not null, primary key
#  name          :string
#  nationality   :string
#  residence     :string
#  telephone     :integer
#  email         :string
#  date_of_birth :date
#  project_id    :integer
#  team_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  sex           :string
#  country_code  :string
#

class Participant < ApplicationRecord

  before_save :titleize_params

  validates :name, presence: true, length: {maximum: 200}
  validates :nationality, presence: true, length: {maximum: 100}
  validates :residence, presence: true, length: {maximum: 100}
  validates :email, presence: true, length: {maximum: 100}, uniqueness: true
  validates :date_of_birth, presence: true
  validates :sex, presence: true,  inclusion: { in: %w(Male Female Other),
    message: "%{value} is not a valid sex" }
  validate :is_older_than_13

  has_many :participant_teams, dependent: :destroy
  has_many :teams, through: :participant_teams

  scope :in_ngo, -> (ngo) {Participant.find(ParticipantTeam.where(team_id:Team.where(project_id:(Ngo.find(ngo)).projects.pluck(:id)).pluck(:id)).pluck(:participant_id))}
  def age
    age = Date.today.year - date_of_birth.year
    age -= 1 if Date.today < date_of_birth + age.years #for days before birthday
    return age
  end

  def is_older_than_13
    if date_of_birth.present? && ((date_of_birth + 13.years) >= Date.today)
      errors.add(:date_of_birth, 'You should be over 13 years old.')
    end
  end

  def join(team, options = {leader: false})
    unless ParticipantTeam.where(participant_id: id, team_id: team.id).count > 0
      ParticipantTeam.create(participant_id: id, team_id: team.id, leader: options[:leader])
    end
  end

  # NGOs related to the participant through some project
  def ngos
    Ngo.where(id: Project.where(id: teams.pluck(:project_id)).pluck(:ngo_id))
  end

  def can_edit?(user)
    Project.find_by(id:self.teams.pluck(:project_id)).can_edit?(user)
  end

  #projects in whitch the participant is
  def projects
    Project.find_by(id: self.teams.pluck(:project_id))
  end


  private

    def titleize_params
      self.name = self.name.titleize
      self.nationality = self.nationality.titleize
      self.residence = self.residence.titleize
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  before_action :set_breadcrumbs
  before_action :set_ngo
  before_action :set_team, only: [:new, :create]
  before_action :authenticate_user!
  before_action :can_edit?, only: [:show, :edit]

  # GET /participants
  def index
    @participants = Participant.in_ngo(@ngo.id)
    @breadcrumbs << { text: t(".index.title")}
  end

  # GET /participants/1
  def show
    @breadcrumbs << { text: @participant.name, path: ngo_participant_path(@ngo.id, @participant) }
  end

  # GET /participants/new
  def new
    @participant = Participant.new
    @participant.nationality = @team.country
    @participant.residence = @team.country
    @participant.team_id = @team.id
    @participant.project_id = @team.project.id
    @breadcrumbs << {text: t(".breadcrumb_new"), path: ngo_new_participant_path(@ngo)}
  end

  # GET /participants/1/edit
  def edit
    @breadcrumbs << {text: @participant.name, path: ngo_participant_path(@ngo, @participant)}
    @breadcrumbs << {text: t(".breadcrumb_edit"), path: edit_ngo_participant_path(@ngo.id)}
  end

  # POST /participants
  def create
    @participant = Participant.new(participant_params)
    if @participant.save
      @participant.reload
      @participant.join(@team)
      flash[:success] = t(".join.success")
      redirect_to @team
    else
      redirect_to ngo_new_participant_path(@ngo)
      # render :new
    end
  end

  # PATCH/PUT /participants/1
  def update
    if @participant.update(participant_params)
      redirect_to ngo_participant_path(@ngo, @participant), notice: t(".success")
    else
      redirect_to ngo_participant_path(@ngo, @participant), error:t(".error")
      # render :edit
    end
  end


  # DELETE /participants/1
  def destroy
    @participant.destroy
    redirect_to ngo_participants_path(@ngo), flash: {success: t(".success")}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    def set_ngo
      @ngo = Ngo.find(params[:ngo_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :nationality, :residence, :country_code, :telephone, :email, :date_of_birth, :sex, :project_id, :team_id)
    end

    def set_breadcrumbs
      set_ngo
      @breadcrumbs =
      [
        { text: t(".set_breadcrumbs.index"), path: root_path },
        { text: @ngo.name, path: ngo_path(@ngo) },
        # { text: t(".set_breadcrumbs.title"), path: ngo_participants_path(@ngo) }
      ]
    end

    def set_team
      @team = params[:team_id].blank? ? nil : Team.find(params[:team_id])
      if(@team && @team.can_edit?(current_user))
        @breadcrumbs << { text: @team.project.name, path: project_path(@team.project) }
        @breadcrumbs << { text: @team.country, path: team_path(@team) }
      else
        redirect_to root_path, notice: "You're not authorized"
      end
    end

    def can_edit?
      unless @participant.can_edit?(current_user)
        redirect_to root_path, notice: "You're not authorized"
      end
    end

end

app/helpers/participants_helper.rb
module ParticipantsHelper
  def sex_for_select(selected)
    if selected.nil?
      options_for_select(["Male", "Female", "Other"])
    else
      options_for_select(["Male", "Female", "Other"], selected)
    end
  end
end

app/views/participants/_form.html.haml
= render 'layouts/errors', resource: @participant
= form_tag @participant.new_record? ? ngo_create_participant_path(@ngo, @team.id) : ngo_participant_path(@ngo.id, @participant), method: @participant.new_record? ? 'post' : 'put' do
  = hidden_field_tag "team_id", @team ? @team.id : nil
  -# = hidden_field_tag "project_id", @team ? @team.project.id : nil
  .form-group
    = label_tag t(".name")
    = text_field_tag 'participant[name]', @participant.try(:name), class: "form-control"
  .form-group
    = label_tag t(".country_of_origin")
    = text_field_tag 'participant[nationality]', @participant.try(:nationality), class: "form-control"
  .form-group
    = label_tag t(".residence_country")
    = text_field_tag 'participant[residence]', @participant.try(:residence), class: "form-control"
  =label_tag t(".telephone")
  .row
    .col-5.col-sm-5
      .form-group
        = text_field_tag 'participant[country_code]', @participant.try(:country_code),:placeholder => t(".placeholder_code"),  class:"form-control"
    .col-7.col-sm-7
      .form-group
        = text_field_tag 'participant[telephone]', @participant.try(:telephone), :placeholder => t(".placeholder_number"), class: "form-control"
  .form-group
    = label_tag t(".email")
    = email_field_tag 'participant[email]', @participant.try(:email), class: "form-control"
  .form-group
    = label_tag t(".date_of_birth")
    = date_field_tag 'participant[date_of_birth]', @participant.try(:date_of_birth), class: "form-control"
  .form-group
    = label_tag t(".sex")
    = select_tag 'participant[sex]', sex_for_select(@participant.try(:selected)), class: "form-control"
  = submit_tag t(".save_button"), class: "btn btn-primary"

app/views/participants/_participant.html.haml
%li.list-group-item
  .row
    .col-12.col-md-9.offset-md-1
      = link_to ngo_participant_path(@ngo, participant) do
        %h3=participant.name
      .text-muted (#{participant.nationality} / #{participant.residence})
      %p #{participant.age} #{t(".years")}
    .col-12.col-md-2.d-flex.flex-column.align-items-end
      %p.mt-auto
        -if user_signed_in? &&  current_user.can_edit?(participant)
          -if participant.can_edit?(current_user)
            = link_to t(".edit"), edit_ngo_participant_path(@ngo.id, participant), class: "card-link"
            = link_to t(".delete"), ngo_participant_path(@ngo, participant), method: "delete", class: "card-link text-danger", data: { confirm: t(".data_confirm")}

app/views/participants/_participant_details.html.haml
.card
  .card-body
    %h1.text-center.mt-3.mb-5=participant.name
    %table.table
      %tbody
        %tr
          %th{scope: 'row'}=t(".country_of_origin")
          %td=participant.nationality
        %tr
          %th{scope: 'row'}=t(".residence_country")
          %td=participant.residence
        %tr
          %th{scope: 'row'}=t(".telephone")
          %td (+#{participant.country_code}) #{participant.telephone}
        %tr
          %th{scope: 'row'}=t(".email")
          %td=participant.email
        %tr
          %th{scope: 'row'}=t(".date_of_birth")
          %td=participant.date_of_birth
        %tr
          %th{scope: 'row'}=t(".age")
          %td=participant.age
        %tr
          %th{scope: 'row'}=t(".sex")
          %td=participant.sex
  .card-footer.text-center
    = link_to t(".edit"), edit_ngo_participant_path(@ngo.id, participant), class: "btn btn-primary mt-3"
    = link_to t(".delete"), ngo_participant_path(@ngo.id, participant), method:'delete', class: "btn btn-danger mt-3", data: { confirm: t(".data_confirm")}

app/views/participants/edit.html.haml
.row.mt-4.mb-4
  .col-md-4.offset-md-4
    %h1.text-center.mb-4= t(".title")
    = render 'form'

app/views/participants/index.html.haml
.row.bottom-bar-container
  .col-12.col-md-8.offset-md-2
    %h1.text-center.mt-4.mb-4=t(".title")
    %ul.list-group
      = render @participants

app/views/participants/new.html.haml
.row.mt-4.mb-4
  .col-md-4.offset-md-4
    %h1.text-center.mb-4= t(".title")
    = render 'form'

app/views/participants/show.html.haml
.row
  .col-12.col-md-4.offset-md-2
    = render 'participant_details', participant: @participant
  .col-12.col-md-4
    .card
      .card-body
        %p
          %h2.mb-4=t(".title")
          - if @participant.teams.count == 0
            .alert.alert-warning= t(".alert")
          - else
            .list-group
              - @participant.teams.each do |team|
                =link_to project_path(team.project.id), class: 'list-group-item list-group-item-action' do
                  =team.project.name + " (" + team.country + ")"
                  .small.text-muted
                    #{team.project.city} (#{team.project.country}) #{team.project.start_day} - #{team.project.final_day}