config/routes.rb
Rails.application.routes.draw do

  resources :ngos, except: [:index] do

    resources :requests
    resources :projects, except: [:index, :show, :edit, :update, :destroy]
    # Projects
    get 'search', to: 'projects#search', as: :project_search
    get 'projects', to: 'ngos#projects', as: :projects, on: :member


    post 'join', to: 'ngos#join', as: :join, on: :member
    get 'join-ngo', to: 'ngos#select', as: :join, on: :collection
    put 'make_admin', to: 'ngos#make_admin', as: :make_admin
    put 'make_worker', to: 'ngos#make_worker', as: :make_worker
    put 'stoping_admin', to: 'ngos#stoping_admin', as: :stoping_admin
    delete 'destroy_association', to: 'ngos#destroy_association', as: :destroy_association, on: :member

    resources :participants, except: [:new, :create]
    #resources :participants, except: [:new, :create]

    get 'team/:team_id/participants/new', to: 'participants#new', as: :new_participant
    post 'team/:team_id/participants', to: 'participants#create', as: :create_participant
  end

  get 'my-ngos', to: 'ngos#my_ngos', as: :my_ngos

  resources :teams, except: :index do
    member do
      put 'add-participant/:participant_id', to: 'teams#add_participant', as: :add_participant
      put 'remove-participant_team/:participant_id', to: 'teams#remove_participant', as: :remove_participant
      put 'make-leader/:participant_id', to: 'teams#make_leader', as: :make_leader
      put 'make-regular/:participant_id', to: 'teams#make_regular', as: :make_regular
    end
  end

  resources :projects, only: [:index, :show, :edit, :update, :destroy, :add_user, :delete_user] do
    member do
      put 'add_user', to: 'projects#add_user', as: :add_user
      put 'delete_user', to: 'projects#delete_user', as: :delete_user
    end
  end

  get 'search', to: 'projects#search', as: :project_search
  delete 'handle-request', to: 'requests#handle', as: :handle_request
  get 'requests', to: 'requests#index', as: :requests

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  as :user do
    get     'sign-up', to: 'devise/registrations#new', as: :sign_up
    get     'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign-out', to: 'devise/sessions#destroy', as: :sign_out
    get    'profile',  to: 'devise/registrations#edit', as: :profile
  end

  get 'not-found', to: 'pages#not_found', as: :not_found
  get '/change_locale/:locale', to: 'locales#change_locale', as: :change_locale

  root 'pages#home'


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  name       :string
#  start_day  :date
#  final_day  :date
#  city       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :string
#  code       :string
#  country    :string
#  ngo_id     :integer
#

class Project < ApplicationRecord

  validates :category, presence: true, length: {maximum:100}
  validates :name, presence: true, length: {maximum: 200}
  validates :city, presence: true, length: {maximum: 100}
  validates :code, presence: true, length: {maximum: 100}
  validates :country, presence: true, length: {maximum: 100}
  validates :start_day, presence:true
  validates :final_day, presence:true

  validate :final_later_than_start
  has_many :teams, dependent: :destroy, inverse_of: :project
  has_many :participans
  belongs_to :ngo
  has_many :project_users
  # translates :category, :name, :city, :code, :country, :start_day, :final_day
  # attribute :category
  # attribute :name
  # attribute :city
  # attribute :code
  # attribute :country
  # attribute :start_day
  # attribute :final_day
  # globalize_accessors locales: [:en, :es], attributes: [:category, :name, :city, :code, :country, :start_day, :final_day]

  scope :current, -> {where('start_day < ?',  Time.now).where('final_day > ?', Time.now) }
  scope :future, -> {where('start_day > ?',  Time.now)}
  scope :past, -> {where('final_day < ?',  Time.now)}
  #scope :with_user, (user_id) -> {} # Lista de Project que están asociados al user (tanto worker como admin)
  #scope :with_worker, (user_id) -> {} # Lista de Project que tienen asociado ese worker

  def final_later_than_start
    return if [final_day.blank?, start_day.blank?].any?
    if final_day < start_day
      errors.add(:final_day, 'Debe ser superior a la fecha inicio')
    end
  end

  def has_worker?(user_id)
    ProjectUser.where(project_id: self.id, user_id: user_id).count > 0
  end

  def can_edit?(user)
    ngo.is_admin?(user) || self.has_worker?(user.id)
  end

  # add_worker
  # 1. Comprueba que el user que le pasan es worker de la ngo a la que pertenece este proyecto
  # 2. Si está ya asociado, no hace nada
  # 3. Si se cumple 1 y no est asociado, lo asocia
  def add_worker(user_id)
    user_id = user_id.to_i
    if !self.ngo.is_admin?(User.find(user_id)) && !self.has_worker?(user_id) && self.ngo.workers.pluck(:id).include?(user_id)
      ProjectUser.create(project_id: self.id, user_id: user_id)
      return true
    else
      return false
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy, :add_user, :delete_user]
  before_action :set_ngo, except: [:index, :search]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_admin, only: [:new, :edit, :create, :update, :destroy, :add_user, :delete_user]
  before_action :set_breadcrumbs
  # GET /projects
  # GET /projects.json
  def index
    @message_when_empty =t(".empty_message")
    @active = params[:list] ? params[:list] : 'all'
    case @active
    when 'future'
      @projects = Project.future
    when 'past'
      @projects = Project.past
    when 'current'
      @projects = Project.current
    else
      @projects = Project.all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @breadcrumbs << {text: @project.name}
  end

  # GET /projects/new
  def new
    @breadcrumbs << {text: t(".breadcrumb_new"), path: new_ngo_project_path(@ngo)}
    @project = Project.new
    @project.ngo = @ngo
  end

  # GET /projects/1/edit
  def edit
    @breadcrumbs << {text: @project.name, path: project_path(@project) }
    @breadcrumbs << {text: t(".breadcrumb_edit"), path: edit_project_path(@project.ngo) }
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.city = @project.city.titleize
    @project.name = @project.name.titleize
    @project.ngo = @ngo
      if @project.save
        redirect_to project_path(@project), flash: {success: t(".success")}
      else
        render :new
      end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to project_path(@project), success:t(".success")
    else
      render :edit
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, flash: {success: t(".success") }}
      format.json { head :no_content }
    end
  end

  def search
    @projects = Project.all
    @query = params[:query]
    @start_day = params[:start_day]
    @final_day = params[:final_day]
    @city = params[:city]
    @ngo_id = params[:ngo_id]

    unless @query.blank?
      @projects = Project.all.where("name like ?", "%"+@query+"%")
    end
    unless @start_day.blank?
      @projects = @projects.where("start_day >= ?", @start_day)
    end
    unless @final_day.blank?
      @projects = @projects.where("final_day <= ?", @final_day)
    end
    unless @city.blank?
      @projects = @projects.where(city: @city)
    end
    unless @ngo_id.blank?
      @projects = @projects.where(ngo_id: @ngo_id)
    end
  end

  def add_user
    if @project.has_worker?(params[:user])
      redirect_to project_path(@project), flash: {success:"User has already added"}
    else
      if @project.add_worker(params[:user])
       # if @project.add_worker(params[:user]) ...
       redirect_to project_path(@project), flash: {success:"Successfully added"}
     else
       redirect_to project_path(@project), flash: {error:"User was not added"}
     end
    end
  end

  def delete_user
    if @project.has_worker?(params[:user])
      ProjectUser.where(project_id: @project.id, user_id: params[:user]).destroy_all
      redirect_to project_path(@project), flash: {success:"Successfully destroyed"}
    else
      redirect_to project_path(@project), flash: {success:"User has already destroyed"}
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.

    def set_ngo
      @ngo= Ngo.where(id: params[:ngo_id]).first || @project.try(:ngo)
      unless @ngo
        redirect_to not_found_path
      end
    end

    def set_project
      @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to not_found_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      form_params = params.require(:project).permit(:category, :name, :city, :code, :country)
      if params[:project][:dates] && params[:project][:dates] != ""
        dates = params[:project][:dates].split(" ")
        form_params[:start_day] = dates[0].to_date
        form_params[:final_day] = dates[1].to_date
      else
        form_params[:start_day] = nil
        form_params[:final_day] = nil
      end
      form_params[:ngo_id] = @project.try(:ngo_id) or @ngo.id
      return form_params
    end

    def set_breadcrumbs
      @breadcrumbs = @ngo ? [
        {text: t(".set_breadcrumbs.index"), path: root_path },
        {text: @ngo.name, path: ngo_path(@ngo)},
        {text: t(".set_breadcrumbs.title"), path: ngo_projects_path(@ngo)}
        ] : [
        {text: t(".set_breadcrumbs.index"), path: root_path },
        {text: t(".set_breadcrumbs.title"), path: projects_path }
        ]
    end

    def check_admin
      unless @ngo.is_admin?(current_user)
        redirect_to projects_path, flash: { notice: t('.error')}
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def categories_for_select
    ['KA1', 'KA2','KA3']
  end

  def project_lists
    ['all', 'current', 'future', 'past']
  end
end

app/views/projects/_form.html.haml
= form_for destination do |f|
  = render 'layouts/errors', resource: @project
  .form-group
    = f.label t(".category")
    = f.select :category, categories_for_select, {}, class: "form-control"
  .form-group
    = f.label :ngo_id
    %br
    = link_to @project.ngo.name, @project.ngo
  .form-group
    = f.label t(".name")
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label t(".code")
    = f.text_field :code, class: "form-control"
  %h4
    =t(".h4")
    %small.text-muted=t(".text_muted")

    = text_field_tag "project[dates]", nil, class: "form-control", id: "daterange"
    :javascript
      $(document).ready(function() {
        $('input[id="daterange"]').daterangepicker({
        "locale": {
        "format": "DD-MM-YYYY",
         "separator": " "
        }
        });
      });
  .form-group
    = f.label t(".country")
    = f.text_field :country, class: "form-control"
  .form-group
    = f.label t(".city")
    = f.text_field :city, class: "form-control"

  = f.submit t(".save_button"), class: "btn btn-primary"

app/views/projects/_project.html.haml
%li.list-group-item.d-flex.justify-content-between.align-items-center
  = link_to project.name, defined?(ngo) ? project_path(project, ngo: true) : project_path(project)
  .row
    - if user_signed_in? && project.ngo.is_admin?(current_user)
      = link_to t('.edit'), edit_project_path(project), class: "btn btn-primary mr-1"
      = link_to t('.delete'), project_path(project), method: "delete", class: "btn btn-danger", data: { confirm: "Are your sure?"}

app/views/projects/_project_search_form.html.haml
.navbar.navbar-expand.navbar-light.bg-light
  .row.col-12
    .col-12.col-md-6
      %ul.nav.navbar-nav
        %h3=t('.title')
        - project_lists.each do |list_name|
          %li.nav-item{class: @active == list_name ? 'active' : ''}
            = link_to t('.'+list_name), projects_path(list: list_name), class: "nav-link"

    .col-12.col-md-6
      = form_tag @ngo ? ngo_project_search_path(@ngo) : project_search_path, class: "form-inline", method: "get" do
        = text_field_tag "query", @query || "", class:"form-control mr-sm-2 accordion", type:"search", placeholder:t(".search_placeholder"), "aria-label": "Search"
        %button.btn.btn-primary{"data-target" => "#demo", "data-toggle" => "collapse", :type => "button", class: "ml-2 mr-2"}=t(".button_advanced")
        = submit_tag t(".button_search"), class: "btn btn-success"
        - if defined?(ngo_id)
          = hidden_field_tag 'ngo_id', ngo_id
        #demo.collapse
          .form-group.pl-2.mb-1.mt-1
            .row
              .col-5
                = label_tag "start_day", t(".start_day")
              .col-7
                = date_field_tag "start_day", @start_day || "", class: "form-control"
          .form-group.pl-2.mb-1
            .row
              .col-5
                = label_tag "final_day", t(".final_day")
              .col-7
                = date_field_tag "final_day", @final_day || "", class: "form-control"
          .form-group.pl-2
            .row
              .col-5
                = label_tag "city", t(".city")
              .col-1
                = text_field_tag "city", @city || "", class: "form-control", placeholder: t(".city")

app/views/projects/_projects_list.html.haml
= render 'projects/project_search_form', ngo_id: defined?(ngo_id) ? ngo_id : nil
.row.bottom-bar-container
  .col-12.col-md-4.offset-md-4
    %h1.text-center=title
    - if projects.empty?
      .alert.alert-warning=@message_when_empty
    - else
      %ul.list-group
        = render projects

app/views/projects/all.html.haml
= render 'projects/project_search_form'
= render 'projects_list', title: "#{t(".title")}", projects:@projects

app/views/projects/edit.html.haml
.row
  .col-md-4.offset-md-4
    %h1=t(".title")
    = render 'form', destination: @project

app/views/projects/index.html.haml
-# = render 'projects/project_search_form'
= render 'projects/projects_list', title:"#{t(".title")} ", projects: @projects, ngo: false

app/views/projects/new.html.haml
.row
  .col-md-4.offset-md-4
    %h1=t(".title")
    = render 'form', destination: [@ngo, @project]

app/views/projects/search.html.haml
= render 'projects/project_search_form'
- if (@query.blank? && @start_day.blank? && @final_day.blank? && @city.blank?)
  .alert.alert-warning=t(".no_field")
- else
  -if @projects
    %h2.text-center.mb-4="#{t(".search_result")} #{@query} #{@start_day} #{@final_day} #{@city}"
    - if @projects.count == 0
      .alert.alert-info=t(".alert")
    - else
      .row
        .col-12.col-md-4.offset-md-4
          .list-group#search-results
            = render @projects

app/views/projects/show.html.haml
%h1.text-center.mt-4.mb-4=@project.name

.row
  .col-12.col-md-4.offset-md-1
    .card
      .card-body
        %table.table.table-borderless
          %thead
            %tr
              %th.text-center{scope: 'col', colspan: '2'}=t('.details')
          %tbody
            %tr
              %th{scope: 'row'}=t(".ngo")
              %td=@project.ngo.name
            %tr
              %th{scope: 'row'}=t(".category")
              %td=@project.category
            %tr
              %th{scope: 'row'}=t(".code")
              %td=@project.code
            %tr
              %th{scope: 'row'}=t(".country")
              %td=@project.country
            %tr
              %th{scope: 'row'}=t(".city")
              %td=@project.city
            %tr
              %th.text-center{scope: 'col', colspan: '2'}
                =t('.project_dates')
                %br
                %span.text-muted=t('.no_travel_days')
            %tr
              %th{scope: 'row'}=t(".start_day")
              %td=@project.start_day
            %tr
              %th{scope: 'row'}=t(".final_day")
              %td=@project.final_day

    - if user_signed_in? && @project.ngo.is_admin?(current_user)
      .row
        .col.text-center
          = link_to t(".edit"), edit_project_path(@project), class: "btn btn-primary mt-3"
          = link_to t(".back"), projects_path, class: "btn btn-success mt-3"


  .col-md-4.offset-md-1
    - if user_signed_in? && @project.ngo.is_admin?(current_user)
      %h4 Add/Delete workers to this project
      = collection_check_boxes :user, :id, @project.ngo.workers, :id, :name do |w|
        = w.label class: "check-box mr-2" do
          = w.object.name
          -if @project.has_worker?(w.object.id)
            = link_to "Delete", delete_user_project_path(@project, user:w.object.id), method:"put", class:"text-danger"
          -else
            = link_to "Add", add_user_project_path(@project, user:w.object.id), method:"put"

    %br
    - if user_signed_in? && @project.ngo.is_admin?(current_user) || user_signed_in? &&  @project.has_worker?(current_user.id)
      = link_to t(".new"), new_team_path(project_id: @project.id), method: "get", class: "btn btn-success mb-2"
      %h3=t(".title")
      -if @project.teams.count==0
        .alert.alert-info=t(".no_teams")
      -else
        .accordion#accordion
          = render @project.teams
    - else
      .alert.alert-warning #{t(".alert_not_authorize")}