config/routes.rb
Rails.application.routes.draw do

  resources :ngos, except: [:index] do

    resources :requests
    resources :projects, except: [:index, :show, :edit, :update, :destroy]
    # Projects
    get 'search', to: 'projects#search', as: :project_search
    get 'projects', to: 'ngos#projects', as: :projects, on: :member


    post 'join', to: 'ngos#join', as: :join, on: :member
    get 'join-ngo', to: 'ngos#select', as: :join, on: :collection
    put 'make_admin', to: 'ngos#make_admin', as: :make_admin
    put 'make_worker', to: 'ngos#make_worker', as: :make_worker
    put 'stoping_admin', to: 'ngos#stoping_admin', as: :stoping_admin
    delete 'destroy_association', to: 'ngos#destroy_association', as: :destroy_association, on: :member

    resources :participants, except: [:new, :create]
    #resources :participants, except: [:new, :create]

    get 'team/:team_id/participants/new', to: 'participants#new', as: :new_participant
    post 'team/:team_id/participants', to: 'participants#create', as: :create_participant
  end

  get 'my-ngos', to: 'ngos#my_ngos', as: :my_ngos

  resources :teams, except: :index do
    member do
      put 'add-participant/:participant_id', to: 'teams#add_participant', as: :add_participant
      put 'remove-participant_team/:participant_id', to: 'teams#remove_participant', as: :remove_participant
      put 'make-leader/:participant_id', to: 'teams#make_leader', as: :make_leader
      put 'make-regular/:participant_id', to: 'teams#make_regular', as: :make_regular
    end
  end

  resources :projects, only: [:index, :show, :edit, :update, :destroy, :add_user, :delete_user] do
    member do
      put 'add_user', to: 'projects#add_user', as: :add_user
      put 'delete_user', to: 'projects#delete_user', as: :delete_user
    end
  end

  get 'search', to: 'projects#search', as: :project_search
  delete 'handle-request', to: 'requests#handle', as: :handle_request
  get 'requests', to: 'requests#index', as: :requests

  # User routes
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  as :user do
    get     'sign-up', to: 'devise/registrations#new', as: :sign_up
    get     'sign-in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign-out', to: 'devise/sessions#destroy', as: :sign_out
    get    'profile',  to: 'devise/registrations#edit', as: :profile
  end

  get 'not-found', to: 'pages#not_found', as: :not_found
  get '/change_locale/:locale', to: 'locales#change_locale', as: :change_locale

  root 'pages#home'


    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_breadcrumbs.html.haml
-unless @breadcrumbs.blank?
  %nav{"aria-label" => "breadcrumb"}
    %ol.breadcrumb
      - @breadcrumbs.each_with_index do |breadcrumb, i|
        - if i < @breadcrumbs.size - 1
          %li.breadcrumb-item
            = link_to breadcrumb[:text], breadcrumb[:path]
        - else
          %li.breadcrumb-item.active{"aria-current" => "page"}=breadcrumb[:text]
          

app/views/layouts/_errors.html.haml
- if resource.errors.any?
  .alert.alert-danger
    %h2=t('.error_message', count: resource.errors.count, model: resource.model_name.human)
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: "alert  alert-dismissible fade show " + flash_class(key), role: "alert"}
    = value
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  = link_to t(".index"), root_path, class: 'navbar-brand'

  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      - if user_signed_in?
        %li.navbar-item{class: active_class(projects_path)}
          = link_to t(".projects"), projects_path, class: "nav-link"

        -unless request.path == '/my-ngos' || request.path == '/projects' || request.path == '/requests' || request.path == '/'
          %li.navbar-item
            -# {class: active_class(ngo_participants_path(@ngo))}
            -# = link_to t(".participants"), ngo_participants_path(@ngo), class: "nav-link"
        -# - if !(current_page?(:controller => 'ngos', :action => 'my_ngos'))
        %li.dropdown
          .navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "link"}
            NGO
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}
            %li.navbar-item
              -# {class: active_class(ngo_participants_path(@ngo))}
              = link_to t(".menu_items.new"), new_ngo_path, class: "dropdown-item"
            %li.navbar-item
              -# {class: active_class(ngo_participants_path(@ngo))}
              = link_to t(".menu_items.myNgos"), my_ngos_path, class: "dropdown-item"
            %li
              = link_to t(".menu_items.join"), join_ngos_path, class: "dropdown-item"

        - if Ngo.with_admin(current_user.id).count > 0
          %li.navbar-item{class: active_class(requests_path)}
            = link_to t(".requests"), requests_path, class: "nav-link"

  .nav.navbar-right.ml-auto
    - if I18n.locale == :en
      = link_to "Español", change_locale_path(:es), {class: "nav-link"}
    - else
      = link_to "English", change_locale_path(:en), {class: "nav-link"}
    - if user_signed_in?
      .dropdown.mr-5
        %button#dropdownMenuButton.btn.btn-primary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
          -if I18n.locale == :en
            My Account
          -else
            Mi Cuenta
        %ul.dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
          %li{class: "nav-item active"}
            = link_to t(".profile"), profile_path, class: "dropdown-item"
          %li
            = link_to t(".sign_out"), sign_out_path, method: "delete", class: "dropdown-item"
    - else
      = link_to t(".sign_in"), user_session_path, class: "btn btn-primary mt-3"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %script{:src => "https://cdn.jsdelivr.net/jquery/latest/jquery.min.js", :type => "text/javascript"}
    %script{:src => "https://cdn.jsdelivr.net/momentjs/latest/moment.min.js", :type => "text/javascript"}
    %script{:src => "https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js", :type => "text/javascript"}
    %link{:href => "https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css", :rel => "stylesheet", :type => "text/css"}/


    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width", :name => "viewport"}/
    %title LogistaProject
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    

  %body
    = render 'layouts/header'
    = render 'layouts/breadcrumbs'
    = render 'layouts/flash_messages'
    -# = render 'layouts/errors'
    .container-fluid.mb-5
      = yield